/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Time = IDL.Int;
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'patientId' : IDL.Nat,
  'isActive' : IDL.Bool,
  'billDate' : Time,
  'totalAmount' : IDL.Nat,
  'billNumber' : IDL.Text,
  'items' : IDL.Text,
  'paidAmount' : IDL.Nat,
});
export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'potency' : IDL.Text,
  'minStockLevel' : IDL.Nat,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'unitPrice' : IDL.Nat,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'chiefComplaints' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'state' : IDL.Text,
  'medicalHistory' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'patientCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const Visit = IDL.Record({
  'id' : IDL.Nat,
  'prescription' : IDL.Text,
  'patientId' : IDL.Nat,
  'visitDate' : Time,
  'diagnosis' : IDL.Text,
  'isActive' : IDL.Bool,
  'notes' : IDL.Text,
  'followUpDate' : IDL.Opt(Time),
  'chiefComplaint' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ClinicSettings = IDL.Record({
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'doctorName' : IDL.Text,
  'clinicName' : IDL.Text,
  'qualification' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBill' : IDL.Func([Bill], [IDL.Nat], []),
  'addMedicine' : IDL.Func([Medicine], [IDL.Nat], []),
  'addPatient' : IDL.Func([Patient], [IDL.Nat], []),
  'addVisit' : IDL.Func([Visit], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBill' : IDL.Func([IDL.Nat], [], []),
  'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
  'deletePatient' : IDL.Func([IDL.Nat], [], []),
  'deleteVisit' : IDL.Func([IDL.Nat], [], []),
  'getBillsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicSettings' : IDL.Func([], [ClinicSettings], ['query']),
  'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
  'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
  'initSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPatients' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
  'updateBill' : IDL.Func([IDL.Nat, Bill], [], []),
  'updateClinicSettings' : IDL.Func([ClinicSettings], [], []),
  'updateMedicine' : IDL.Func([IDL.Nat, Medicine], [], []),
  'updatePatient' : IDL.Func([IDL.Nat, Patient], [], []),
  'updateVisit' : IDL.Func([IDL.Nat, Visit], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Time = IDL.Int;
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'patientId' : IDL.Nat,
    'isActive' : IDL.Bool,
    'billDate' : Time,
    'totalAmount' : IDL.Nat,
    'billNumber' : IDL.Text,
    'items' : IDL.Text,
    'paidAmount' : IDL.Nat,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'potency' : IDL.Text,
    'minStockLevel' : IDL.Nat,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'unitPrice' : IDL.Nat,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'chiefComplaints' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'state' : IDL.Text,
    'medicalHistory' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'patientCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Visit = IDL.Record({
    'id' : IDL.Nat,
    'prescription' : IDL.Text,
    'patientId' : IDL.Nat,
    'visitDate' : Time,
    'diagnosis' : IDL.Text,
    'isActive' : IDL.Bool,
    'notes' : IDL.Text,
    'followUpDate' : IDL.Opt(Time),
    'chiefComplaint' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ClinicSettings = IDL.Record({
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'doctorName' : IDL.Text,
    'clinicName' : IDL.Text,
    'qualification' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBill' : IDL.Func([Bill], [IDL.Nat], []),
    'addMedicine' : IDL.Func([Medicine], [IDL.Nat], []),
    'addPatient' : IDL.Func([Patient], [IDL.Nat], []),
    'addVisit' : IDL.Func([Visit], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBill' : IDL.Func([IDL.Nat], [], []),
    'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
    'deletePatient' : IDL.Func([IDL.Nat], [], []),
    'deleteVisit' : IDL.Func([IDL.Nat], [], []),
    'getBillsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicSettings' : IDL.Func([], [ClinicSettings], ['query']),
    'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
    'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
    'initSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPatients' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
    'updateBill' : IDL.Func([IDL.Nat, Bill], [], []),
    'updateClinicSettings' : IDL.Func([ClinicSettings], [], []),
    'updateMedicine' : IDL.Func([IDL.Nat, Medicine], [], []),
    'updatePatient' : IDL.Func([IDL.Nat, Patient], [], []),
    'updateVisit' : IDL.Func([IDL.Nat, Visit], [], []),
  });
};

export const init = ({ IDL }) => { return []; };