/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'paymentStatus' : PaymentStatus,
  'patientId' : bigint,
  'isActive' : boolean,
  'billDate' : Time,
  'totalAmount' : bigint,
  'billNumber' : string,
  'items' : string,
  'paidAmount' : bigint,
}
export interface ClinicSettings {
  'address' : string,
  'phone' : string,
  'doctorName' : string,
  'clinicName' : string,
  'qualification' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Medicine {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'potency' : string,
  'minStockLevel' : bigint,
  'quantity' : bigint,
  'category' : string,
  'unitPrice' : bigint,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'chiefComplaints' : string,
  'name' : string,
  'isActive' : boolean,
  'state' : string,
  'medicalHistory' : string,
  'address' : string,
  'gender' : Gender,
  'patientCode' : string,
  'phone' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : bigint,
  'prescription' : string,
  'patientId' : bigint,
  'visitDate' : Time,
  'diagnosis' : string,
  'isActive' : boolean,
  'notes' : string,
  'followUpDate' : [] | [Time],
  'chiefComplaint' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBill' : ActorMethod<[Bill], bigint>,
  'addMedicine' : ActorMethod<[Medicine], bigint>,
  'addPatient' : ActorMethod<[Patient], bigint>,
  'addVisit' : ActorMethod<[Visit], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBill' : ActorMethod<[bigint], undefined>,
  'deleteMedicine' : ActorMethod<[bigint], undefined>,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'deleteVisit' : ActorMethod<[bigint], undefined>,
  'getBillsByPatient' : ActorMethod<[bigint], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinicSettings' : ActorMethod<[], ClinicSettings>,
  'getLowStockMedicines' : ActorMethod<[], Array<Medicine>>,
  'getMedicine' : ActorMethod<[bigint], Medicine>,
  'getPatient' : ActorMethod<[bigint], Patient>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitsByPatient' : ActorMethod<[bigint], Array<Visit>>,
  'initSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPatients' : ActorMethod<[string], Array<Patient>>,
  'updateBill' : ActorMethod<[bigint, Bill], undefined>,
  'updateClinicSettings' : ActorMethod<[ClinicSettings], undefined>,
  'updateMedicine' : ActorMethod<[bigint, Medicine], undefined>,
  'updatePatient' : ActorMethod<[bigint, Patient], undefined>,
  'updateVisit' : ActorMethod<[bigint, Visit], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];