/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ClinicSettings {
    address: string;
    phone: string;
    doctorName: string;
    clinicName: string;
    qualification: string;
}
export interface Medicine {
    id: bigint;
    name: string;
    isActive: boolean;
    potency: string;
    minStockLevel: bigint;
    quantity: bigint;
    category: string;
    unitPrice: bigint;
}
export interface Bill {
    id: bigint;
    paymentStatus: PaymentStatus;
    patientId: bigint;
    isActive: boolean;
    billDate: Time;
    totalAmount: bigint;
    billNumber: string;
    items: string;
    paidAmount: bigint;
}
export interface Visit {
    id: bigint;
    prescription: string;
    patientId: bigint;
    visitDate: Time;
    diagnosis: string;
    isActive: boolean;
    notes: string;
    followUpDate?: Time;
    chiefComplaint: string;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface Patient {
    id: bigint;
    age: bigint;
    chiefComplaints: string;
    name: string;
    isActive: boolean;
    state: string;
    medicalHistory: string;
    address: string;
    gender: Gender;
    patientCode: string;
    phone: string;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBill(bill: Bill): Promise<bigint>;
    addMedicine(medicine: Medicine): Promise<bigint>;
    addPatient(patient: Patient): Promise<bigint>;
    addVisit(visit: Visit): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBill(id: bigint): Promise<void>;
    deleteMedicine(id: bigint): Promise<void>;
    deletePatient(id: bigint): Promise<void>;
    deleteVisit(id: bigint): Promise<void>;
    getBillsByPatient(patientId: bigint): Promise<Array<Bill>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClinicSettings(): Promise<ClinicSettings>;
    getLowStockMedicines(): Promise<Array<Medicine>>;
    getMedicine(id: bigint): Promise<Medicine>;
    getPatient(id: bigint): Promise<Patient>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitsByPatient(patientId: bigint): Promise<Array<Visit>>;
    initSampleData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPatients(searchTerm: string): Promise<Array<Patient>>;
    updateBill(id: bigint, bill: Bill): Promise<void>;
    updateClinicSettings(settings: ClinicSettings): Promise<void>;
    updateMedicine(id: bigint, medicine: Medicine): Promise<void>;
    updatePatient(id: bigint, patient: Patient): Promise<void>;
    updateVisit(id: bigint, visit: Visit): Promise<void>;
}
import type { Bill as _Bill, Gender as _Gender, Patient as _Patient, PaymentStatus as _PaymentStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Visit as _Visit } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBill(arg0: Bill): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBill(to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBill(to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMedicine(arg0: Medicine): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(arg0);
            return result;
        }
    }
    async addPatient(arg0: Patient): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatient(to_candid_Patient_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatient(to_candid_Patient_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addVisit(arg0: Visit): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVisit(to_candid_Visit_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVisit(to_candid_Visit_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBill(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async deletePatient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deleteVisit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisit(arg0);
            return result;
        }
    }
    async getBillsByPatient(arg0: bigint): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillsByPatient(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillsByPatient(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClinicSettings(): Promise<ClinicSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicSettings();
            return result;
        }
    }
    async getLowStockMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockMedicines();
            return result;
        }
    }
    async getMedicine(arg0: bigint): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicine(arg0);
            return result;
        }
    }
    async getPatient(arg0: bigint): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_Patient_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_Patient_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitsByPatient(arg0: bigint): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitsByPatient(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitsByPatient(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchPatients(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatients(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatients(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBill(arg0: bigint, arg1: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(arg0, to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(arg0, to_candid_Bill_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClinicSettings(arg0: ClinicSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClinicSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClinicSettings(arg0);
            return result;
        }
    }
    async updateMedicine(arg0: bigint, arg1: Medicine): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, arg1);
            return result;
        }
    }
    async updatePatient(arg0: bigint, arg1: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, to_candid_Patient_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, to_candid_Patient_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVisit(arg0: bigint, arg1: Visit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisit(arg0, to_candid_Visit_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisit(arg0, to_candid_Visit_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Bill_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Visit_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visit): Visit {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentStatus: _PaymentStatus;
    patientId: bigint;
    isActive: boolean;
    billDate: _Time;
    totalAmount: bigint;
    billNumber: string;
    items: string;
    paidAmount: bigint;
}): {
    id: bigint;
    paymentStatus: PaymentStatus;
    patientId: bigint;
    isActive: boolean;
    billDate: Time;
    totalAmount: bigint;
    billNumber: string;
    items: string;
    paidAmount: bigint;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n16(_uploadFile, _downloadFile, value.paymentStatus),
        patientId: value.patientId,
        isActive: value.isActive,
        billDate: value.billDate,
        totalAmount: value.totalAmount,
        billNumber: value.billNumber,
        items: value.items,
        paidAmount: value.paidAmount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    chiefComplaints: string;
    name: string;
    isActive: boolean;
    state: string;
    medicalHistory: string;
    address: string;
    gender: _Gender;
    patientCode: string;
    phone: string;
}): {
    id: bigint;
    age: bigint;
    chiefComplaints: string;
    name: string;
    isActive: boolean;
    state: string;
    medicalHistory: string;
    address: string;
    gender: Gender;
    patientCode: string;
    phone: string;
} {
    return {
        id: value.id,
        age: value.age,
        chiefComplaints: value.chiefComplaints,
        name: value.name,
        isActive: value.isActive,
        state: value.state,
        medicalHistory: value.medicalHistory,
        address: value.address,
        gender: from_candid_Gender_n23(_uploadFile, _downloadFile, value.gender),
        patientCode: value.patientCode,
        phone: value.phone
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    prescription: string;
    patientId: bigint;
    visitDate: _Time;
    diagnosis: string;
    isActive: boolean;
    notes: string;
    followUpDate: [] | [_Time];
    chiefComplaint: string;
}): {
    id: bigint;
    prescription: string;
    patientId: bigint;
    visitDate: Time;
    diagnosis: string;
    isActive: boolean;
    notes: string;
    followUpDate?: Time;
    chiefComplaint: string;
} {
    return {
        id: value.id,
        prescription: value.prescription,
        patientId: value.patientId,
        visitDate: value.visitDate,
        diagnosis: value.diagnosis,
        isActive: value.isActive,
        notes: value.notes,
        followUpDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.followUpDate)),
        chiefComplaint: value.chiefComplaint
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Visit>): Array<Visit> {
    return value.map((x)=>from_candid_Visit_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n21(_uploadFile, _downloadFile, x));
}
function to_candid_Bill_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bill): _Bill {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Patient_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Patient): _Patient {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Visit_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visit): _Visit {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    prescription: string;
    patientId: bigint;
    visitDate: Time;
    diagnosis: string;
    isActive: boolean;
    notes: string;
    followUpDate?: Time;
    chiefComplaint: string;
}): {
    id: bigint;
    prescription: string;
    patientId: bigint;
    visitDate: _Time;
    diagnosis: string;
    isActive: boolean;
    notes: string;
    followUpDate: [] | [_Time];
    chiefComplaint: string;
} {
    return {
        id: value.id,
        prescription: value.prescription,
        patientId: value.patientId,
        visitDate: value.visitDate,
        diagnosis: value.diagnosis,
        isActive: value.isActive,
        notes: value.notes,
        followUpDate: value.followUpDate ? candid_some(value.followUpDate) : candid_none(),
        chiefComplaint: value.chiefComplaint
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentStatus: PaymentStatus;
    patientId: bigint;
    isActive: boolean;
    billDate: Time;
    totalAmount: bigint;
    billNumber: string;
    items: string;
    paidAmount: bigint;
}): {
    id: bigint;
    paymentStatus: _PaymentStatus;
    patientId: bigint;
    isActive: boolean;
    billDate: _Time;
    totalAmount: bigint;
    billNumber: string;
    items: string;
    paidAmount: bigint;
} {
    return {
        id: value.id,
        paymentStatus: to_candid_PaymentStatus_n3(_uploadFile, _downloadFile, value.paymentStatus),
        patientId: value.patientId,
        isActive: value.isActive,
        billDate: value.billDate,
        totalAmount: value.totalAmount,
        billNumber: value.billNumber,
        items: value.items,
        paidAmount: value.paidAmount
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    chiefComplaints: string;
    name: string;
    isActive: boolean;
    state: string;
    medicalHistory: string;
    address: string;
    gender: Gender;
    patientCode: string;
    phone: string;
}): {
    id: bigint;
    age: bigint;
    chiefComplaints: string;
    name: string;
    isActive: boolean;
    state: string;
    medicalHistory: string;
    address: string;
    gender: _Gender;
    patientCode: string;
    phone: string;
} {
    return {
        id: value.id,
        age: value.age,
        chiefComplaints: value.chiefComplaints,
        name: value.name,
        isActive: value.isActive,
        state: value.state,
        medicalHistory: value.medicalHistory,
        address: value.address,
        gender: to_candid_Gender_n7(_uploadFile, _downloadFile, value.gender),
        patientCode: value.patientCode,
        phone: value.phone
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
